services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    env_file: ./.env
    environment:
       POSTGRES_USER: $DB_USER
       POSTGRES_PASSWORD: $DB_ROOT_PASSWORD
       POSTGRES_DB: $DB_DATABASE
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - D:\dev\psql_temp:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - my-network

  app:
    build: .
    container_name: app
    depends_on:
      - db
    restart: always
    env_file: ./.env

    environment:
      SPRING_APPLICATION_NAME: EnqMS
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/$DB_DATABASE
      SPRING_DATASOURCE_USERNAME: $DB_USER
      SPRING_DATASOURCE_PASSWORD: $DB_ROOT_PASSWORD
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: $SPRING_LOCAL_PORT
    ports:
        - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    networks:
      - my-network

volumes:
  psql_temp:

networks:
  my-network:
