---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBN/lZjq6CZjkI3fX+adyOe7BVgHr/gHkFsN50QhwkMvbfvth5pfKWj9v7AoJw9XfHSM3BBoDnaglGUQX5g7v9p73gAWJ+xX+0Z1i9+DIVyeGcVgKRX2yzQ/z9cxgca+vE8JfND2fkZdnRne9qp/IjhhXOn3oTmiFOmKvnYVCPfImQBee7Jkny/5nk2qIEOmdOdh384dc0mIIZL21I6lP/nQ/gj259f9PbnCgZfSGT1AQ/YuIziRagmmxjSw4L1VjZ00cOZaMf8baHF4msOqf4YNcW8zO8KhBA8HY5O98pHoukBwewOa1xd9xHOeD3CN3ENHUhB29hdhmkwJJAUhzgNou6l0iJeMAnOTpWgwMllY2On5aPSvC2HXK1k7mQgd9I00dx+/8gzaiQvOJRT3GkbBnyAzOG5a+aHuoqwh7DQ7KOovgKqctD8qtSqV8lIIYpqPexEvzgTVfqMOnhLiZTAckmwT9wPmi0N+bRNf/XwtTdVNnu6Y/qb8HA/GM7OZV4aTvBgrlVsUWrVYh1G5Ey93BiUNepCKVOtqGFt3VUJwYGpcdexlPNTNBUjEtanOyQ8cWh3CgQLSlTc/saeQMrb0SZ00bGUT8aTccA6TyPmNuf2vuu8iVmxQqlniHjmaC6vEqfx6uXNqoYKNIpl7WYKiW3IELOpZ85HQdYqNF1S5MhqwNJMxxdO6XlibLO+BfsRyGjrRA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: default
    type: Opaque
