spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/afterorder
    username: postgres
    password: sohel
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      defer-datasource-initialization: true
  sql:
    init:
      mode: always
